package base65536

var (
	adjectives = []string{
		"different", "used", "important", "every", "large", "available", "popular",
		"able", "basic", "known", "various", "difficult", "several", "united",
		"historical", "hot", "useful", "mental", "scared", "additional",
		"emotional", "old", "political", "similar", "healthy", "financial",
		"medical", "traditional", "federal", "entire", "strong", "actual",
		"significant", "successful", "electrical", "expensive", "pregnant",
		"intelligent", "interesting", "poor", "happy", "responsible", "cute",
		"helpful", "recent", "willing", "nice", "wonderful", "impossible",
		"serious", "huge", "rare", "technical", "typical", "competitive",
		"critical", "electronic", "immediate", "aware", "educational",
		"environmental", "global", "legal", "relevant", "accurate", "capable",
		"dangerous", "dramatic", "efficient", "powerful", "foreign", "hungry",
		"practical", "psychological", "severe", "suitable", "numerous",
		"sufficient", "unusual", "consistent", "cultural", "existing", "famous",
		"pure", "afraid", "obvious", "careful", "latter", "unhappy", "acceptable",
		"aggressive", "boring", "distinct", "eastern", "logical", "reasonable",
		"strict", "administrative", "automatic", "civil", "former", "massive",
		"southern", "unfair", "visible", "alive", "angry", "desperate", "exciting",
		"friendly", "lucky", "realistic", "sorry", "ugly", "unlikely", "anxious",
		"comprehensive", "curious", "impressive", "informal", "inner", "pleasant",
		"sexual", "sudden", "terrible", "unable", "weak", "wooden", "asleep",
		"confident", "conscious", "decent", "embarrassed", "guilty", "lonely",
		"mad", "nervous", "odd", "remarkable", "substantial", "suspicious", "tall",
		"tiny", "more", "some", "all", "many", "most", "other", "such", "even",
		"new", "just", "good", "any", "each", "much", "own", "great", "another",
		"same", "few", "free", "right", "still", "best", "public", "human", "both",
		"local", "sure", "better", "general", "specific", "enough", "long",
		"small", "less", "high", "certain", "little", "common", "next", "simple",
		"hard", "past", "big", "possible", "particular", "real", "major",
		"personal", "current", "left", "national", "least", "natural", "physical",
		"short", "last", "single", "individual", "main", "potential",
		"professional", "international", "lower", "open", "according",
		"alternative", "special", "working", "true", "whole", "clear", "dry",
		"easy", "cold", "commercial", "full", "low", "primary", "worth",
		"necessary", "positive", "present", "close", "creative", "green", "late",
		"fit", "glad", "proper", "complex", "content", "due", "effective",
		"middle", "regular", "fast", "independent", "original", "wide",
		"beautiful", "complete", "active", "negative", "safe", "visual", "wrong",
		"ago", "quick", "ready", "straight", "white", "direct",
	}
	nouns = []string{
		"people", "history", "way", "art", "world", "information", "map", "family",
		"government", "health", "system", "computer", "meat", "year", "thanks",
		"music", "person", "reading", "method", "data", "food", "understanding",
		"theory", "law", "bird", "literature", "problem", "software", "control",
		"knowledge", "power", "ability", "economics", "love", "internet",
		"television", "science", "library", "nature", "fact", "product", "idea",
		"temperature", "investment", "area", "society", "activity", "story",
		"industry", "media", "thing", "oven", "community", "definition", "safety",
		"quality", "development", "language", "management", "player", "variety",
		"video", "week", "security", "country", "exam", "movie", "organization",
		"equipment", "physics", "analysis", "policy", "series", "thought", "basis",
		"boyfriend", "direction", "strategy", "technology", "army", "camera",
		"freedom", "paper", "environment", "child", "instance", "month", "truth",
		"marketing", "university", "writing", "article", "department",
		"difference", "goal", "news", "audience", "fishing", "growth", "income",
		"marriage", "user", "combination", "failure", "meaning", "medicine",
		"philosophy", "teacher", "communication", "night", "chemistry", "disease",
		"disk", "energy", "nation", "road", "role", "soup", "advertising",
		"location", "success", "addition", "apartment", "education", "math",
		"moment", "painting", "politics", "attention", "decision", "event",
		"property", "shopping", "student", "wood", "competition", "distribution",
		"entertainment", "office", "population", "president", "unit", "category",
		"cigarette", "context", "introduction", "opportunity", "performance",
		"driver", "flight", "length", "magazine", "newspaper", "relationship",
		"teaching", "cell", "dealer", "finding", "lake", "member", "message",
		"phone", "scene", "appearance", "association", "concept", "customer",
		"death", "discussion", "housing", "inflation", "insurance", "mood",
		"woman", "advice", "blood", "effort", "expression", "importance",
		"opinion", "payment", "reality", "responsibility", "situation", "skill",
		"statement", "wealth", "application", "city", "county", "depth", "estate",
		"foundation", "grandmother", "heart", "perspective", "photo", "recipe",
		"studio", "topic", "collection", "depression", "imagination", "passion",
		"percentage", "resource", "setting", "ad", "agency", "college",
		"connection", "criticism", "debt", "description", "memory", "patience",
		"secretary", "solution", "administration", "aspect", "attitude",
		"director", "personality", "psychology", "recommendation", "response",
		"selection", "storage", "version", "alcohol", "argument", "complaint",
		"contract", "emphasis", "highway", "loss", "membership", "possession",
		"preparation", "steak", "union", "agreement", "cancer", "currency",
		"employment", "engineering", "entry", "interaction", "mixture",
		"preference", "region", "republic", "tradition", "virus", "actor",
		"classroom",
	}
)
