package base65536

var (
	adjectives = []string{
		"able", "aged", "ancient", "autumn", "big", "billowing", "bitter", "black",
		"blue", "bold", "brave", "brief", "bright", "brilliant", "brisk", "broken",
		"calm", "careful", "charming", "chilly", "cold", "cool", "courageous",
		"crimson", "damp", "dapper", "dark", "dawn", "dazzling", "delicate",
		"divine", "dry", "eager", "empty", "falling", "fancy", "fast", "fearless",
		"feisty", "floating", "floral", "fragrant", "frosty", "frozen", "gentle",
		"giant", "glass", "green", "happy", "hidden", "holy", "icy", "jolly",
		"joyful", "late", "light", "lingering", "little", "lively", "long", "loud",
		"majestic", "merry", "misty", "modern", "morning", "muddy", "nameless",
		"natural", "new", "old", "orange", "pale", "patient", "peaceful",
		"polished", "proud", "purple", "quiet", "red", "restless", "rough", "shy",
		"silent", "small", "snowy", "solitary", "sparkling", "spring", "still",
		"summer", "thawing", "timely", "twilight", "wandering", "weathered",
		"white", "wild", "winter", "wispy", "withered", "young", "different",
		"used", "important", "every", "large", "available", "popular", "basic",
		"known", "various", "difficult", "several", "united", "historical", "hot",
		"useful", "mental", "scared", "additional", "emotional", "political",
		"similar", "healthy", "financial", "medical", "traditional", "federal",
		"entire", "strong", "actual", "significant", "successful", "electrical",
		"expensive", "pregnant", "intelligent", "interesting", "poor",
		"responsible", "cute", "helpful", "recent", "willing", "nice", "wonderful",
		"impossible", "serious", "huge", "rare", "technical", "typical",
		"competitive", "critical", "electronic", "immediate", "aware",
		"educational", "environmental", "global", "legal", "relevant", "accurate",
		"capable", "dangerous", "dramatic", "efficient", "powerful", "foreign",
		"hungry", "practical", "psychological", "severe", "suitable", "numerous",
		"sufficient", "unusual", "consistent", "cultural", "existing", "famous",
		"pure", "afraid", "obvious", "latter", "unhappy", "acceptable",
		"aggressive", "boring", "distinct", "eastern", "logical", "reasonable",
		"strict", "administrative", "automatic", "civil", "former", "massive",
		"southern", "unfair", "visible", "alive", "angry", "desperate", "exciting",
		"friendly", "lucky", "realistic", "sorry", "ugly", "unlikely", "anxious",
		"comprehensive", "curious", "impressive", "informal", "inner", "pleasant",
		"sexual", "sudden", "terrible", "unable", "weak", "wooden", "asleep",
		"confident", "conscious", "decent", "embarrassed", "guilty", "lonely",
		"mad", "nervous", "odd", "remarkable", "substantial", "suspicious", "tall",
		"tiny", "more", "some", "all", "many", "most", "other", "such", "even",
		"just", "good", "any", "each", "much", "own", "great",
	}
	nouns = []string{
		"bird", "blossom", "breeze", "brook", "butterfly", "cloud", "darkness",
		"dawn", "dew", "dream", "dust", "feather", "field", "fire", "firefly",
		"flower", "fog", "forest", "frog", "frost", "glade", "glitter", "grape",
		"grass", "haze", "hill", "lake", "leaf", "meadow", "meteor", "moon",
		"morning", "mountain", "nebula", "night", "paper", "pine", "planet",
		"pond", "pulsar", "rain", "resonance", "river", "rock", "sea", "shadow",
		"shape", "silence", "sky", "smoke", "snow", "snowflake", "sound", "star",
		"stone", "sun", "sunset", "surf", "thunder", "tree", "vine", "violet",
		"voice", "water", "waterfall", "wave", "wildflower", "wind", "people",
		"history", "way", "art", "world", "information", "map", "family",
		"government", "health", "system", "computer", "meat", "year", "thanks",
		"music", "person", "reading", "method", "data", "food", "understanding",
		"theory", "law", "literature", "problem", "software", "control",
		"knowledge", "power", "ability", "economics", "love", "internet",
		"television", "science", "library", "nature", "fact", "product", "idea",
		"temperature", "investment", "area", "society", "activity", "story",
		"industry", "media", "thing", "oven", "community", "definition", "safety",
		"quality", "development", "language", "management", "player", "variety",
		"video", "week", "security", "country", "exam", "movie", "organization",
		"equipment", "physics", "analysis", "policy", "series", "thought", "basis",
		"boyfriend", "direction", "strategy", "technology", "army", "camera",
		"freedom", "environment", "child", "instance", "month", "truth",
		"marketing", "university", "writing", "article", "department",
		"difference", "goal", "news", "audience", "fishing", "growth", "income",
		"marriage", "user", "combination", "failure", "meaning", "medicine",
		"philosophy", "teacher", "communication", "chemistry", "disease", "disk",
		"energy", "nation", "road", "role", "soup", "advertising", "location",
		"success", "addition", "apartment", "education", "math", "moment",
		"painting", "politics", "attention", "decision", "event", "property",
		"shopping", "student", "wood", "competition", "distribution",
		"entertainment", "office", "population", "president", "unit", "category",
		"cigarette", "context", "introduction", "opportunity", "performance",
		"driver", "flight", "length", "magazine", "newspaper", "relationship",
		"teaching", "cell", "dealer", "finding", "member", "message", "phone",
		"scene", "appearance", "association", "concept", "customer", "death",
		"discussion", "housing", "inflation", "insurance", "mood", "woman",
		"advice", "blood", "effort", "expression", "importance", "opinion",
		"payment", "reality", "responsibility", "situation", "skill", "statement",
		"wealth", "application", "city", "county", "depth", "estate",
	}
)
